### ISSUE TITLE
tiny_slam does not build on indigo jade or kinetic ROS buildfarm

### ISSUE THREAD

**Issue by tfoote** [OSLL/tiny-slam-ros-cpp#24]
It looks like a missing dependency declaration.

http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_uT64__tiny_slam__ubuntu_trusty_amd64__binary/110/console

```
00:37:14 [100%] Building CXX object CMakeFiles/tiny_slam.dir/src/tiny_slam/tiny_slam.cpp.o
00:37:14 /usr/bin/x86_64-linux-gnu-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"tiny_slam\" -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2  -I/opt/ros/indigo/include    -o CMakeFiles/tiny_slam.dir/src/tiny_slam/tiny_slam.cpp.o -c /tmp/binarydeb/ros-indigo-tiny-slam-0.1.2/src/tiny_slam/tiny_slam.cpp
00:37:16 /tmp/binarydeb/ros-indigo-tiny-slam-0.1.2/src/tiny_slam/tiny_slam.cpp:6:36: fatal error: nav_msgs/OccupancyGrid.h: No such file or directory
00:37:16  #include <nav_msgs/OccupancyGrid.h>
00:37:16                                     ^
00:37:16 compilation terminated.
00:37:22 make[4]: *** [CMakeFiles/tiny_slam.dir/src/tiny_slam/tiny_slam.cpp.o] Error 1
00:37:22 make[3]: *** [CMakeFiles/tiny_slam.dir/all] Error 2
00:37:22 make[2]: make[4]: Leaving directory `/tmp/binarydeb/ros-indigo-tiny-slam-0.1.2/obj-x86_64-linux-gnu'
00:37:22 *** [all] Error 2
00:37:22 make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-tiny-slam-0.1.2/obj-x86_64-linux-gnu'
00:37:22 dh_auto_build: make -j1 returned exit code 2
00:37:22 make[2]: Leaving directory `/tmp/binarydeb/ros-indigo-tiny-slam-0.1.2/obj-x86_64-linux-gnu'
00:37:22 make[1]: *** [override_dh_auto_build] Error 2
00:37:22 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-tiny-slam-0.1.2'
00:37:22 make: *** [build] Error 2
00:37:22 dpkg-buildpackage: error: debian/rules build gave error exit status 2
00:37:22 E: Building failed
00:37:22 Traceback (most recent call last):
00:37:22   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
00:37:22     subprocess.check_call(cmd, cwd=source_dir)
00:37:22   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
00:37:22     raise CalledProcessError(retcode, cmd)
00:37:22 # END SUBSECTION
00:37:22 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-tiny-slam']' returned non-zero exit status 1
00:37:22 
00:37:22 --------------------------------------------------------------------------------------------------
00:37:22 `apt-src build ros-indigo-tiny-slam` failed.
00:37:22 This is usually because of an error building the package.
00:37:22 The traceback from this failure (just above) is printed for completeness, but you can ignore it.
00:37:22 You should look above `E: Building failed` in the build log for the actual cause of the failure.
00:37:22 --------------------------------------------------------------------------------------------------
00:37:22 
```

**Comment by tfoote** [comment]
This is failing for the same reason on jade and kinetic: http://build.ros.org:8080/view/Jbin_uT64/job/Jbin_uT64__tiny_slam__ubuntu_trusty_amd64__binary/137/console

http://build.ros.org:8080/view/Kbin_uX64/job/Kbin_uX64__tiny_slam__ubuntu_xenial_amd64__binary/118/console
